/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 5);
        next();
    });
};
function f(__callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    console.log("5.2. f_()");
    switch ("foo") {
      case "foo":
        console.log("5.2. case 1");
        g(function(err, __result_3) {
            if (err) {
                return __callback_2(err)
            };
            return __callback_2(null, __result_3);
        });
        break;
      default:
        console.log("5.2. default");
        return __callback_2(null, 7);
        break;
    };
};
function g(__callback_4) {
    __callback_4 = (__callback_4 || __throw_1);
    console.log("5.2. g_()");
    return __callback_4(null, 5);
};
function __throw_1(err) {if (err) {throw err}};
