/*** Generated by streamline.js - DO NOT EDIT ***/
function f(callback) {
    g();
    if (callback) {
        return callback(null)
    };
};
exports.g_called = false;
function g() {
    exports.g_called = true;
};
exports.f = f;
