/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_null(err);
        assert.is_true((result === 5));
        next();
    });
};
function f(callback) {
    g(function(err, result1) {
        if (err) {
            if (callback) {
                return callback(err)
            } else {
                throw err
            }
        };
        if (callback) {
            return callback(null, result1)
        } else {
            return
        };
    });
};
function g(callback) {
    return callback(null, 5);
};
