/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 6);
        next();
    });
};
function f(__callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    return g(function(err, __result_3) {
        if (err) {
            return __callback_2(err)
        };
        if ((__result_3 === 5)) {
            return __callback_2(null, 6);
        }
    ;
        return __callback_2(null);
    });
};
function g(__callback_4) {
    __callback_4 = (__callback_4 || __throw_1);
    return __callback_4(null, 5);
    return __callback_4(null);
};
function __throw_1(err) {if (err) {throw err}};
