/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_null(err);
        assert.equal(result, 5);
        assert.is_true(w_called);
        assert.is_true(x_called);
        assert.is_true(y_called);
        assert.is_true(z_called);
        next();
    });
};
function f(__callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    x(function(err) {
        if (err) {
            return __callback_2(err)
        };
        __for_loop_3();
        function __for_loop_3() {
            return y(function(err, __result_5) {
                if (err) {
                    return __callback_2(err)
                };
                if (__result_5) {
                    __then_block_6();
                }
                 else {
                    __else_block_7();
                }
            ;
                function __then_block_6() {
                    w(function(err) {
                        if (err) {
                            return __callback_2(err)
                        };
                        z(function(err) {
                            if (err) {
                                return __callback_2(err)
                            };
                            setTimeout(__for_loop_3, 0);
                            __rest_block_8();
                        });
                    });
                };
                function __else_block_7() {
                    __rest_4();
                    __rest_block_8();
                };
                function __rest_block_8() {
                
                };
            });
        };
        function __rest_4() {
            return __callback_2(null, 5);
        };
    });
};
var w_called = false;
function w(__callback_9) {
    __callback_9 = (__callback_9 || __throw_1);
    w_called = true;
    return __callback_9(null);
};
var x_called = false;
function x(__callback_10) {
    __callback_10 = (__callback_10 || __throw_1);
    x_called = true;
    return __callback_10(null);
};
var y_called = false;
function y(__callback_11) {
    __callback_11 = (__callback_11 || __throw_1);
    if (y_called) {
        __then_block_12();
    }
     else {
        __else_block_13();
    }
;
    function __then_block_12() {
        return __callback_11(null, false);
    };
    function __else_block_13() {
        y_called = true;
        return __callback_11(null, true);
    };
    function __rest_block_14() {
        return __callback_11(null);
    };
};
var z_called = false;
function z(__callback_15) {
    __callback_15 = (__callback_15 || __throw_1);
    z_called = true;
    return __callback_15(null);
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
