/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_null(err);
        assert.equal(result, 5);
        assert.is_true(w_called);
        assert.is_true(x_called);
        assert.is_true(y_called);
        assert.is_true(z_called);
        next();
    });
};
function f(callback) {
    x(function(err, __async_result_1) {
        if (err) {
            if (callback) {
                return callback(err)
            } else {
                throw err
            }
        };
        __async_result_1;
        setTimeout(__while_loop_2, 0);
        function __while_loop_2() {
            y(function(err, __async_result_3) {
                if (err) {
                    if (callback) {
                        return callback(err)
                    } else {
                        throw err
                    }
                };
                if (__async_result_3) {
                    w(function(err, __async_result_4) {
                        if (err) {
                            if (callback) {
                                return callback(err)
                            } else {
                                throw err
                            }
                        };
                        __async_result_4;
                        z(function(err, __async_result_5) {
                            if (err) {
                                if (callback) {
                                    return callback(err)
                                } else {
                                    throw err
                                }
                            };
                            __async_result_5;
                            setTimeout(__while_loop_2, 0);
                        });
                    });
                }
                 else {
                    if (callback) {
                        return callback(null, 5)
                    } else {
                        return
                    };
                }
            ;
            });
        };
    });
};
var w_called = false;
function w(callback) {
    w_called = true;
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
var x_called = false;
function x(callback) {
    x_called = true;
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
var y_called = false;
function y(callback) {
    if (y_called) {
        if (callback) {
            return callback(null, false)
        } else {
            return
        };
    }
     else {
        y_called = true;
        if (callback) {
            return callback(null, true)
        } else {
            return
        };
    }
;
};
var z_called = false;
function z(callback) {
    z_called = true;
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
