/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 6);
        next();
    });
};
function f(__callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    g(function(err, __result_3) {
        if (err) {
            return __callback_2(err)
        };
        switch (__result_3) {
          case 5:
            return __callback_2(null, 6);
          default:
            return __callback_2(null, 7);
        };
    });
};
function g(__callback_4) {
    __callback_4 = (__callback_4 || __throw_1);
    return __callback_4(null, 5);
};
function __throw_1(err) {if (err) {throw err}};
