/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    pow(2, 3, function(err, result) {
        assert.equal(result, 8);
        next();
    });
};
function pow(base, exponent, callback) {
    function g(callback) {
        if (callback) {
            return callback(null, exponent--)
        };
    };
    var n = 1;
    next10();
    function next10() {
        g(function(err, result11) {
            if (err) {
                if (callback) {
                    return callback(err)
                } else {
                    throw err
                }
            };
            if ((result11 > 0)) {
                n *= base;
                next10();
            }
             else {
                if (callback) {
                    return callback(null, n)
                };
            }
        ;
        });
    };
};
