/*** Generated by streamline.js - DO NOT EDIT ***/
function f(callback) {
    if (callback) {
        return callback(new Error())
    } else {
        throw err
    };
    if (callback) {
        return callback(null)
    };
};
exports.f = f;
