/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    pow(2, 3, function(err, result) {
        assert.equal(result, 8);
        next();
    });
};
function pow(base, exponent, callback) {
    function count(callback) {
        if (callback) {
            return callback(null, exponent--)
        } else {
            return
        };
    };
    function times(a, b, callback) {
        if (callback) {
            return callback(null, (a * b))
        } else {
            return
        };
    };
    var n = 1;
    setTimeout(while_loop19, 0);
    function while_loop19() {
        count(function(err, result20) {
            if (err) {
                if (callback) {
                    return callback(err)
                } else {
                    throw err
                }
            };
            if ((result20 > 0)) {
                times(n, base, function(err, result21) {
                    if (err) {
                        if (callback) {
                            return callback(err)
                        } else {
                            throw err
                        }
                    };
                    n = result21;
                    setTimeout(while_loop19, 0);
                });
            }
             else {
                if (callback) {
                    return callback(null, n)
                } else {
                    return
                };
            }
        ;
        });
    };
};
