/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_true(g_called);
        next();
    });
};
function f(callback) {
    callback = (callback || __throw_1);
    g();
    return callback(null);
};
var g_called = false;
function g() {
    g_called = true;
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
