/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    sum([3,4,5,], function(err, result) {
        assert.is_null(err);
        assert.equal(result, 12);
        next();
    });
};
function sum(values, __callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    var total = 0;
    var __props_3 = [];
    for (var i in values) {
        __props_3.push(i);
    };
    var __i_4 = 0;
    __for_loop_5();
    function __for_loop_5() {
        if ((__i_4 < __props_3.length)) {
            __then_block_7();
        }
         else {
            __else_block_8();
        }
    ;
        function __then_block_7() {
            i = __props_3[__i_4];
            return plus(total, values[i], function(err, __result_10) {
                if (err) {
                    return __callback_2(err)
                };
                total = __result_10;
                ++__i_4;
                setTimeout(__for_loop_5, 0);
                __rest_block_9();
            });
        };
        function __else_block_8() {
            __rest_6();
            __rest_block_9();
        };
        function __rest_block_9() {
        
        };
    };
    function __rest_6() {
        return __callback_2(null, total);
    };
};
function sum_model(values, callback) {
    var total = 0;
    var _props = [];
    for (i in values) {
        _props.push(i);
    };
    for (var _i = 0; (_i < _props.length); _i++) {
        i = _props[_i];
        total = plus_(total, values[i]);
    };
    return total;
};
function plus(a, b, callback) {
    return callback(null, (a + b));
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
