/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 5);
        assert.is_true(g_called);
        next();
    });
};
function f(callback) {
    try {
        {
            var err = err;
            if (callback) {
                return callback(err)
            } else {
                throw err
            };
        };
    } catch (err) {
        g(function(err, result15) {
            if (err) {
                if (callback) {
                    return callback(err)
                } else {
                    throw err
                }
            };
            result15;
        });
    };
    if (callback) {
        return callback(null, 5)
    } else {
        return
    };
};
var g_called = false;
function g(callback) {
    g_called = true;
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
