/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_null(err);
        assert.equal(result, 5);
        assert.is_true(g_called);
        next();
    });
};
function f(__callback_2) {
    __callback_2 = (__callback_2 || __throw_1);
    __try_block_3();
    function __try_block_3() {
        var main_callback = __callback_2;
        var __callback_2 = function(err, result) {
            (err ? __catch_block_4 : main_callback)(err, result);
        };
        return __callback_2(new Error());
        __rest_block_6();
    };
    function __catch_block_4(err) {
        g(function(err, __result_7) {
            if (err) {
                return __callback_2(err)
            };
            __result_7;
            __rest_block_6();
        });
    };
    function __rest_block_6() {
        return __callback_2(null, 5);
    };
};
var g_called = false;
function g(__callback_8) {
    __callback_8 = (__callback_8 || __throw_1);
    g_called = true;
    return __callback_8(null);
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
