/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        next();
    });
};
var f = function(callback) {
    callback = (callback || __throw_1);
    return callback(null);
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
