/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        next();
    });
};
var f = function(callback) {
    if (callback) {
        return callback(null)
    };
};
