/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 6);
        next();
    });
};
function f(callback) {
    g(function(err, result6) {
        if (err) {
            if (callback) {
                return callback(err)
            } else {
                throw err
            }
        };
        if (callback) {
            return callback(null, (result6 + 1))
        };
    });
};
function g(callback) {
    if (callback) {
        return callback(null, 5)
    };
};
