/*** Generated by Cinch ***/
exports.test = function(next, assert) {
    f(function(err, g) {
        assert.equal(g(), 2);
        next();
    });
};
function f(__callback_2) {
    var x = 1;
    function g() {
        return x;
    };
    return h(function(err, __result_3) {
        if (err) {
            return __callback_2(err)
        };
        __result_3;
        x = 2;
        return __callback_2(null, g);
    });
};
function h(__callback_4) {
    return __callback_4(null);
};
