/*** Generated by streamline.js - DO NOT EDIT ***/
var path = require("path");
var fs = require("fs");
exports.test = function(next, assert) {
    var filename = path.join(__dirname, "test.txt");
    fileLength(filename, function(err, result) {
        assert.equal(result, 5);
        next();
    });
};
function fileLength(path, callback) {
    fs.stat(path, function(err, __async_result_1) {
        if (err) {
            if (callback) {
                return callback(err)
            } else {
                throw err
            }
        };
        if (__async_result_1.isFile()) {
            fs.readFile(path, function(err, __async_result_2) {
                if (err) {
                    if (callback) {
                        return callback(err)
                    } else {
                        throw err
                    }
                };
                if (callback) {
                    return callback(null, __async_result_2.length)
                } else {
                    return
                };
            });
        }
         else {
            {
                var err = new Error((path + " is not a file"));
                if (callback) {
                    return callback(err)
                } else {
                    throw err
                };
            };
        }
    ;
    });
};
