/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_true(g_called);
        next();
    });
};
function f(callback) {
    callback = (callback || __throw_1);
    g(function(err, __result_2) {
        if (err) {
            return callback(err)
        };
        __result_2;
        return callback(null);
    });
};
var g_called = false;
function g(callback) {
    callback = (callback || __throw_1);
    g_called = true;
    return callback(null);
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
