/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.is_null(err);
        assert.is_undefined(result);
        next();
    });
};
function f(callback) {
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
