/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f();
    next();
};
function f(callback) {
    if (callback) {
        return callback(null)
    } else {
        return
    };
};
