/*** Generated by streamline.js - DO NOT EDIT ***/
exports.test = function(next, assert) {
    f(function(err, result) {
        assert.equal(result, 6);
        next();
    });
};
function f(callback) {
    callback = (callback || __throw_1);
    var result;
    g(function(err, __result_2) {
        if (err) {
            return callback(err)
        };
        result = (__result_2 + 1);
        return callback(null, result);
    });
};
function g(callback) {
    callback = (callback || __throw_1);
    return callback(null, 5);
};
function __throw_1(err) {
    if (err) {
        throw err;
    }
;
};
